version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:10.0.2-jdk-node-browsers
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run:
        name: Chmod permissions for gradlew
        command: sudo chmod +x ./gradlew

    - run: gradle dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    # run tests!
    - run:
        name: Run tests
        command: gradle test --info
    - store_artifacts:
        path: build/reports

    - run:
        name: Upload coverage report to codecov
        command: bash <(curl -s https://codecov.io/bash) -Z

    - run:
        name: Build app
        command: gradle jar
    - run:
        name: Package app
        command: gradle customDistZip
    - run: mkdir -p workspace
    - run: gradle properties -q | grep "version:" | awk '{print $2}' > workspace/version.txt
    - persist_to_workspace:
        root: workspace


  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./build/distributions
    - run:
        name: "Get version number"
        command: VERSION=$(cat ./build/distributions/version.txt')
    - run:
        name: "Publish Release on GitHub"
        command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/distributions


workflows:
  version: 2
  build-and-publish:
    jobs:
    - build
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            only: master


